name: Deploy Server to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/server-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Verify Vercel CLI
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "Error: VERCEL_TOKEN is not set"
            exit 1
          fi
          
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Install Dependencies
        run: |
          npm ci
          echo "✅ Dependencies installed successfully!"
          
      - name: Build Project
        run: |
          npm run build
          echo "✅ Project built successfully!"
          
      - name: Deploy to Vercel
        run: |
          vercel deploy --token ${{ secrets.VERCEL_TOKEN }} \
                       --prod \
                       --yes \
                       --scope ${{ secrets.VERCEL_ORG_ID }} \
                       --confirm
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} 