name: Deploy to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - '.github/workflows/vercel-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'

      - name: Verify Vercel Token
        if: env.VERCEL_TOKEN == ''
        run: |
          echo "Error: VERCEL_TOKEN is not set"
          exit 1
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Install Dependencies
        run: |
          cd client
          npm ci
          echo "✅ Dependencies installed successfully"

      - name: Build Project
        run: |
          cd client
          npm run build
          echo "✅ Project built successfully"

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./client
          vercel-args: '--prod' 