name: Deploy to Vercel
on:
  push:
    branches: [ initial-setup, main ]
  pull_request:
    branches: [ initial-setup, main ]

permissions:
  contents: write
  pull-requests: write
  deployments: write
  actions: write

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Print working directory
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Dependencies installed successfully"

      - name: Build project
        run: |
          echo "Building project..."
          npm run build
          echo "Build completed successfully"

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod' 