name: Vercel Deploy
on:
  push:
    branches: [ initial-setup, main ]
  pull_request:
    branches: [ initial-setup, main ]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v3
      
      - name: 显示当前目录
        run: pwd && ls -la
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: 验证 Vercel Token
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "错误: VERCEL_TOKEN 未设置"
            exit 1
          else
            echo "VERCEL_TOKEN 已设置"
          fi
      
      - name: Install Dependencies
        run: |
          echo "开始安装依赖..."
          npm install
          echo "依赖安装完成"
      
      - name: Build Project
        run: |
          echo "开始构建项目..."
          npm run build
          echo "项目构建完成"
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./
        env:
          NODE_ENV: production
          REACT_APP_API_URL: https://api.aplysia.app
          REACT_APP_WS_URL: wss://api.aplysia.app/graphql 