name: Vercel Deploy
on:
  push:
    branches: [ initial-setup ]
  pull_request:
    branches: [ initial-setup ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Verify Vercel Token
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "Error: VERCEL_TOKEN is not set"
            exit 1
          fi
          echo "Vercel token is set"
          
      - name: Install Dependencies
        run: |
          cd client
          npm install
          echo "Dependencies installed successfully"
          
      - name: Build Project
        run: |
          cd client
          npm run build
          echo "Build completed successfully"
          
      - name: Deploy to Vercel
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes --scope ${{ secrets.VERCEL_SCOPE }} --team ${{ secrets.VERCEL_TEAM }}
          echo "Deployment completed" 